
process_validation_datasets:
  differential_expression:
    padj_threshold: 0.1

  power_simulations:
    n_batches:
      Klann: 300
      Morrisv1: 60
      Morrisv2: 100
      Xie: 100
    n_reps: 100
    guide_sd: 0.13
    
benchmark_validation_datasets:
  create_encode_output:
    download_urls:
      gencode.v29lift37: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/GRCh37_mapping/gencode.v29lift37.annotation.gtf.gz"
      gencode.v29: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gtf.gz"
      liftover_chain: "https://hgdownload.cse.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz"
      RefSeq_tss: "https://raw.githubusercontent.com/broadinstitute/ABC-Enhancer-Gene-Prediction/master/reference/RefSeqCurated.170308.bed.CollapsedGeneBounds.TSS500bp.bed"
    encode_datasets:
      ignore_transcripts:
        Xie: NULL
        Morrisv1: NULL
        Morrisv2: NULL
        Klann: NULL
        K562_DC_TAP_Seq: NULL
        HCT116: NULL
        WTC11_DC_TAP_Seq: NULL
        Jurkat: NULL
        GM12878: NULL
      dist_to_TSS: [1000, 1e6]
      annot:
        Xie: "resources/benchmark_validation_datasets/create_encode_output/gencode.v29.annotation.gtf.gz"
        Morrisv1: "resources/benchmark_validation_datasets/create_encode_output/gencode.v29.annotation.gtf.gz"
        Morrisv2: "resources/benchmark_validation_datasets/create_encode_output/gencode.v29.annotation.gtf.gz"
        Klann: "resources/benchmark_validation_datasets/create_encode_output/gencode.v29.annotation.gtf.gz"
        K562_DC_TAP_Seq: "resources/benchmark_validation_datasets/create_encode_output/gencode.v29lift37.annotation.gtf.gz"
        HCT116: "resources/benchmark_validation_datasets/create_encode_output/gencode.v29.annotation.gtf.gz"
        WTC11_DC_TAP_Seq: "resources/benchmark_validation_datasets/create_encode_output/gencode.v29lift37.annotation.gtf.gz"
        Jurkat: "resources/benchmark_validation_datasets/create_encode_output/gencode.v29.annotation.gtf.gz"
        GM12878: "resources/benchmark_validation_datasets/create_encode_output/gencode.v29.annotation.gtf.gz"
      genome_build:
        Xie: "GRCh38"
        Morrisv1: "GRCh38"
        Morrisv2: "GRCh38"
        Klann: "GRCh38"
        K562_DC_TAP_Seq: "hg19"
        HCT116: "GRCh38"
        WTC11_DC_TAP_Seq: "hg19"
        Jurkat: "GRCh38"
        GM12878: "GRCh38"
    metadata:
      Xie:
        cell_type: "K562"
        reference: "Xie et al., 2019"
        gene_ids: "ensembl"
        tss_ctrl_tag: "TSSCtrl"
      Morrisv2:
        cell_type: "K562"
        reference: "Morris et al., 2023"
        gene_ids: "ensembl"
        tss_ctrl_tag: "TSSCtrl"
      Morrisv1:
        cell_type: "K562"
        reference: "Morris et al., 2023"
        gene_ids: "ensembl"
        tss_ctrl_tag: "TSSCtrl"
      Klann:
        cell_type: "K562"
        reference: "Klann et al., 2021"
        gene_ids: "ensembl"
        tss_ctrl_tag: "TSSCtrl"
      K562_DC_TAP_Seq: 
        cell_type: "K562"
        reference: "NNFC_K56_DC_TAP"
        gene_ids: "ensembl"
        tss_ctrl_tag: "TSSCtrl"
      HCT116:
        cell_type: "HCT116"
        reference: "Guckelberger et al., inPrep"
        gene_ids: "symbol"
        tss_ctrl_tag: "TSSCtrl"
      WTC11_DC_TAP_Seq:
        cell_type: "WTC11"
        reference: "WTC11_DC_TAP"
        gene_ids: "ensembl"
        tss_ctrl_tag: "TSSCtrl"
      Jurkat:
        cell_type: "Jurkat"
        reference: "Nasser 2021"
        gene_ids: "symbol"
        tss_ctrl_tag: "TSSCtrl"
      GM12878:
        cell_type: "GM12878"
        reference: "Nasser 2021"
        gene_ids: "symbol"
        tss_ctrl_tag: "TSSCtrl"