
process_validation_datasets:
  differential_expression:
    padj_threshold: 0.1

  power_simulations:
    n_batches:
      Klann: 300
      Morrisv1: 60
      Morrisv2: 100
      Xie: 100
    n_reps: 100
    guide_sd: 0.13
    
benchmark_validation_datasets:
  create_encode_output:
    download_urls:
      gencode.v29: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gtf.gz"
    encode_datasets:
      ignore_transcripts:
        Xie: NULL
        Morrisv1: NULL
        Morrisv2: NULL
        Klann: NULL
        HCT116: NULL
        Jurkat: NULL
        GM12878: NULL
      dist_to_TSS: [1000, 1e6]
      annot:
        Xie: "results/genome_annotation_files/gencode.v29.annotation.gtf.gz"
        Morrisv1: "results/genome_annotation_files/gencode.v29.annotation.gtf.gz"
        Morrisv2: "results/genome_annotation_files/gencode.v29.annotation.gtf.gz"
        Klann: "results/genome_annotation_files/gencode.v29.annotation.gtf.gz"
        HCT116: "results/genome_annotation_files/gencode.v29.annotation.gtf.gz"
        Jurkat: "results/genome_annotation_files/gencode.v29.annotation.gtf.gz"
        GM12878: "results/genome_annotation_files/gencode.v29.annotation.gtf.gz"
      genome_build:
        Xie: "GRCh38"
        Morrisv1: "GRCh38"
        Morrisv2: "GRCh38"
        Klann: "GRCh38"
        HCT116: "GRCh38"
        Jurkat: "GRCh38"
        GM12878: "GRCh38"
    metadata:
      Xie:
        cell_type: "K562"
        reference: "Xie et al., 2019"
        gene_ids: "ensembl"
        tss_ctrl_tag: "TSSCtrl"
      Morrisv2:
        cell_type: "K562"
        reference: "Morris et al., 2023"
        gene_ids: "ensembl"
        tss_ctrl_tag: "TSSCtrl"
      Morrisv1:
        cell_type: "K562"
        reference: "Morris et al., 2023"
        gene_ids: "ensembl"
        tss_ctrl_tag: "TSSCtrl"
      Klann:
        cell_type: "K562"
        reference: "Klann et al., 2021"
        gene_ids: "ensembl"
        tss_ctrl_tag: "TSSCtrl"
      HCT116:
        cell_type: "HCT116"
        reference: "Guckelberger et al., inPrep"
        gene_ids: "symbol"
        tss_ctrl_tag: "TSSCtrl"
      Jurkat:
        cell_type: "Jurkat"
        reference: "Nasser 2021"
        gene_ids: "symbol"
        tss_ctrl_tag: "TSSCtrl"
      GM12878:
        cell_type: "GM12878"
        reference: "Nasser 2021"
        gene_ids: "symbol"
        tss_ctrl_tag: "TSSCtrl"